### ISSUE TITLE
ETA for 1.0

### ISSUE THREAD

**Issue by stof** [php-http/guzzle7-adapter#7]
Guzzle 7 is stable since quite some time now.
Is there anything blocking a 1.0 release of this adapter instead of staying on 0.x (which are special in semver) ?

**Comment by Art4** [comment]
I've successfully tested v0.1.1 with Guzzle 7.2. Can this library considered as stable?

**Comment by dbu** [comment]
right, i tagged https://github.com/php-http/guzzle7-adapter/releases/tag/1.0.0 :tada:
